n1 = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(n1))
print('Só tem espaços?', n1.isspace())
print('Só tem números?', n1.isnumeric())
print('É alfabético?', n1.isalpha())
print('É alfanumérico?', n1.isalnum())
print('Está em maiúscula?', n1.isupper())
print('Está em minúscula?', n1.islower())
print('Está capitalizada?', n1.istitle())
